
service: proj-call
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: wsgi.handler
    layers:
      - arn:aws:lambda:ap-south-1:070824542205:layer:proj-call-lib:1
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

