
service: proj-call
frameworkVersion: '3'

plugins:
  - serverless-python-requirements  # Add this line

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  pythonRequirements:
    dockerizePip: true  # Dockerize the deployment process to ensure compatibility with Lambda
